name: panda
description: A new Flutter project.

publish_to: "none"

version: 1.0.11

environment:
  sdk: ">=2.18.2 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  provider: ^6.0.5
  shared_preferences: ^2.2.0
  google_maps_flutter: ^2.3.1
  geolocator: ^9.0.2
  http: ^1.1.0
  flutter_easyloading: ^3.0.5
  carousel_slider: ^4.2.1
  smooth_page_indicator: ^1.1.0
  flutter_dotenv: ^5.1.0
  flutter_rating_bar: ^4.0.1
  flex_color_picker: ^3.2.2
  image_picker: ^1.0.0
  jwt_decode: ^0.3.1
  search_map_location: ^0.0.6
  flutter_multi_formatter: ^2.11.1
  animated_snack_bar: ^0.3.1
  introduction_screen: ^3.1.9
  skeleton_text: ^3.0.1
  image_cropper: ^5.0.0
  dio: ^5.2.1+1
  flutter_markdown: ^0.6.17
  pull_to_refresh: ^2.0.0
  animations: ^2.0.7
  phone_form_field: ^8.1.0
  auto_size_text: ^3.0.0
  cached_network_image: ^3.2.3
  flutter_colorpicker: ^1.0.3
  intl: ^0.18.0
  url_launcher: ^6.1.12
  flutter_dialogs: ^3.0.0
  google_fonts: ^5.1.0
  amazon_cognito_identity_dart_2: ^3.5.0
  path_provider: ^2.0.15
  location_geocoder: ^1.0.5
  intl_phone_field: ^3.2.0
  intl_phone_number_input: ^0.7.3+1
  empty_widget: ^0.0.5
  flutter_polyline_points: ^1.0.0
  location: ^4.4.0
  firebase_core: ^2.14.0
  firebase_messaging: ^14.6.4
  flutter_local_notifications: ^15.1.0+1
  badges: ^3.1.1
  tutorial_coach_mark: ^1.2.9
  flutter_countdown_timer: ^4.1.0
  time_picker_widget:
    git: https://github.com/ba5liel/time_picker_widget.git
  pinput: ^2.2.31
  flutter_credit_card: ^3.0.7
  # flutter_screenutil: ^5.9.0
  # hive: ^2.2.3
  # hive_flutter: ^1.1.0
  # amplify_flutter: ^1.4.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.13.1
  flutter_lints: ^2.0.0

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/logo.png"
  min_sdk_android: 21 # android min sdk min:16, default 21

dependency_overrides:
  http: ^1.1.0

flutter_native_splash: color:"#ffcccc"
# The following section is specific to Flutter packages.
flutter:
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - .env
    - assets/
